---
title: "weather1"
author: "Riley Feltner"
date: "12/14/2022"
output: html_document
---
#import and begin cleaning
```{r}
weatherdata <- read.csv("fullweatherdataset.csv")
weatherdata$L <- as.numeric(as.character(weatherdata$L))
newdata <- weatherdata[rev(order(weatherdata$L)),]
newdata$X <- gsub("^.{0,5}", "", newdata$X) #omitting the area code or whatever the heck those #'s were
newdata$X <- gsub(".{4}$", "", newdata$X) #same as above but for last 4 characters
newdata <- newdata[c(1,41)]
```

#import big cities 
```{r}
library(tidyverse)
bigcities <- read.csv("Cities.csv")
```

#Sort data
```{r}
bigcities$City <- toupper(bigcities$City)
colnames(newdata)[1] <- "City"

#change some of the names so they match once we merge
newdata[newdata == "BIRMINGHAM A"]<- "BIRMINGHAM"
newdata[newdata == "CHICAG"]<- "CHICAGO"
newdata[newdata == "GREATER CINCINNATI A"]<- "CINCINNATI"
newdata[newdata == "DALLAS-FORT WORTH"]<- "DALLAS"
newdata[newdata == "LOS ANGELES AP"]<- "LOS ANGELES"
newdata[newdata == "MINNEAPOLIS-ST.PAUL"]<- "MINNEAPOLIS"
newdata[newdata == "NEW YORK (JFK AP)"]<- "NEW YORK"
newdata[newdata == "NEW YORK (JFK AP)"]<- "NEW YORK"
newdata[newdata == "SAN FRANCISCO AP"]<- "SAN FRANCISCO"
newdata[newdata == "SAN FRANCISCO AP"]<- "SAN JOSE"
newdata[newdata == "SEATTLE SEA-TAC AP"]<- "SEATTLE"
newdata[newdata == "WASHINGTON DULLES AP,"]<- "WASHINGTON"

mergeddata <- merge(x = bigcities, y = newdata, by = "City", all.x = TRUE)
mergeddata <- na.omit(mergeddata)
mergeddata <- mergeddata[-41,]
mergeddata <- mergeddata[rev(order(mergeddata$L)),] %>% head(10)
```

#Visualize
```{r}
library(ggplot2)
ggplot(data = mergeddata, mapping = aes(x = reorder(City, -L), y = L))+
  geom_col(width = 0.5, alpha = .5, color = "black")+
  theme_classic()+
  coord_cartesian(ylim = c(50, 225))+
  geom_text(aes(label = L), vjust = -0.5, size = 3.0, color = "black")+
  theme(axis.text.x = element_text(size = 8, angle = 45, hjust = 1))+
  labs(title = "Top 10 Major US Cities with the Most Days of Heavy Cloud Cover ",
       x = "",
       y = "Days of Heavy Cloud Cover",
       caption = "Data: noaa.gov | Riley Feltner")
```

